CHUNK_SIZE = 500
CHUNK_OVERLAP = 100

VECTOR_TOP_K = 20
FINAL_TOP_K = 5

RRF_K = 60

EMBEDDING_MODEL = "BAAI/bge-small-en-v1.5"
RERANKER_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"

GENERATION_MODEL = "gemini-3.7-flash"

MAX_RETRIES = 3
RETRY_DELAY = 2

RETRIEVAL_CONFIDENCE_THRESHOLD = 0.0